name: learned_uncertainty
channels:
#   - anaconda
#   - conda-forge
  - defaults
dependencies:
#  - torch=1.13.1
  - absl-py=1.4.0
#   - addict=2.4.0
  - anyio=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - attrs=22.1.0
  - Babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - bleach=4.1.0
#   - bm3d=4.0.1
#   - bm4d=4.2.3
  - brotlipy=0.7.0
#   - cachetools=5.3.1
#   - celluloid=0.2.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - cryptography=38.0.4
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2021.10.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.6
  - docker-pycreds=0.4.0
  - entrypoints=0.4
#   - fastjsonschema=2.16.2
  - flit-core=3.6.0
  - fsspec=2022.11.0
  - gitdb=4.0.7
  - GitPython=3.1.30
  - google-auth=2.22.0
#   - google-auth-oauthlib=0.4.6
#   - grpcio=1.57.0
  - h5py=3.7.0
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - importlib-metadata=4.11.3
#   - importlib-resources=5.2.0
  - ipykernel=6.15.2
  - ipython=7.31.1
#   - ipython-genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - Jinja2=3.1.2
  - json5=0.9.6
#   - jsons=1.6.3
  - jsonschema=4.16.0
  - jupyter=1.0.0
#   - jupyter-client=7.4.8
#   - jupyter-console=6.4.4
#   - jupyter-core=4.11.2
#   - jupyter-server=1.23.4
#   - jupyterlab=3.5.3
#   - jupyterlab-pygments=0.1.2
#   - jupyterlab-server=2.16.5
#   - jupyterlab-widgets=1.0.0
  - kiwisolver=1.4.4
#   - lmdb=1.4.1
  - locket=1.0.0
#   - lpips=0.1.4
  - lxml=4.9.1
#   - Markdown=3.4.4
  - MarkupSafe=2.1.1
  - matplotlib=3.1.3
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
#   - mkl-fft=1.3.0
#   - mkl-random=1.1.0
#   - mkl-service=2.3.0
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - networkx=2.6.3
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numpy=1.18.5
#   - nvidia-cublas-cu11=11.10.3.66
#   - nvidia-cuda-nvrtc-cu11=11.7.99
#   - nvidia-cuda-runtime-cu11=11.7.99
#   - nvidia-cudnn-cu11=8.5.0.96
  - oauthlib=3.2.2
  - olefile=0.46
#   - opencv-contrib-python=4.8.0.76
  - packaging=22.0
  - pandas=1.0.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pathtools=0.1.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - Pillow=7.1.2
  - pip=20.1.1
  - pkgutil-resolve-name=1.3.10
  - ply=3.11
#   - prometheus-client=0.14.1
  - prompt-toolkit=3.0.20
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
#   - pyasn1=0.5.0
#   - pyasn1-modules=0.3.0
  - pycparser=2.21
  - Pygments=2.11.2
  - pyOpenSSL=22.0.0
  - pyparsing=3.0.9
  - PyQt5-sip=12.11.0
  - pyrsistent=0.18.0
  - PySocks=1.7.1
  - python-dateutil=2.8.2
  - pytz=2022.7
  - PyWavelets=1.3.0
  - PyYAML=6.0
  - pyzmq=23.2.0
  - qtconsole=5.4.0
  - QtPy=2.2.0
  - requests=2.28.1
#   - requests-oauthlib=1.3.1
  - rsa=
